
version: '3.4'

services:
  highscoreapi:
    image: highscoreapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7208:80"    
    networks:
      - highscropeapi-network
    depends_on:
      - "sqldata"    
  sqldata:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=${sqldatapass}
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    networks:
      - highscropeapi-network       
networks:
  highscropeapi-network:
    driver: bridge